### ISSUE TITLE
Crash in citations

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/rfc-camelot-holy-grenade#20]
From https://github.com/metanorma/rfc-camelot-holy-grenade/pull/17

There's a crash due to relaton-render:

```
undefined method `children' for #<RelatonBib::FormattedRef:0x000000012632e9d0 @format="application/x-isodoc+xml", @language=nil, @script=nil, @content="G. Chapman, J. Cleese, E. Idle, T. Gilliam, T. Jones, M. Palin. 1975. <em>Monty Python and the Holy Grail</em>.">

          return embedded ? f.children.to_xml : doc.to_xml
                             ^^^^^^^^^
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.6.1/lib/relaton/render/general/render.rb:119:in `parse'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.6.1/lib/relaton/render/general/render.rb:114:in `render'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ietf-3.2.4/lib/isodoc/ietf/references.rb:68:in `bibitem_render'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ietf-3.2.4/lib/isodoc/ietf/references.rb:60:in `block in ietf_bibitem'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
```

**Comment by opoudjis** [comment]
Debugged treatment of formattedref in relaton-render.

Also need to debug metanorma-ietf treatment of formattedref.

**Comment by opoudjis** [comment]
Now compiles
